joe-bell/cva

README.md

So, I just forgot how this syntax works 😅 I came back here to look it up, and I just noticed I missed `"with"` or `"during"`, or basically any word that would make this a proper sentence.
For my defense, I'm not a native English speaker :P
---

Add missing word to README

---

README.md

Updates example to `<script setup>`
It's the recommended syntax if using SFC and Composition API and much better TS support!
https://vuejs.org/api/sfc-script-setup.html#script-setup
---

docs: update vue example to <script setup>

---

.github/workflows/commitlint.yml

Noticed that `commitlint` failed in #70, this PR aims to unblock that
---

Upgrade Commitlint

---

README.md

Use Explicit React HTML Types

---

README.md

- Add @nauvalazhar's nevoim recommendation (thanks @nauvalazhar!)
- Recommend `tailwind-merge` (cc @dcastil)
---

Extend Tailwind Recommendations 

---

packages/class-variance-authority/package.json
packages/cva/.config/.swcrc
packages/cva/README.md
packages/cva/package.json
packages/cva/src/index.ts
packages/cva/src/types.ts
pnpm-lock.yaml

Utilizes SWC minification for the upcoming `cva` package; supporting the addition of new features without sacrificing bundlesize 
**before vs. after**
Thank you @kdy1 🔥
---

Enable SWC Minification for `cva`

---

.github/workflows/ci.yml
.github/workflows/commitlint.yml
docs/package.json
docs/pages/docs/getting-started.mdx
examples/astro-with-tailwindcss/package.json
examples/react-with-css-modules/package.json
examples/react-with-tailwindcss/package.json
examples/svelte/package.json
examples/vue/package.json
package.json
packages/class-variance-authority/package.json
packages/cva/package.json
pnpm-lock.yaml

- Closes #125
- Closes #127 
- Closes #128 
---

Support for TypeScript 5

---

docs/package.json
examples/astro-with-tailwindcss/package.json
examples/react-with-css-modules/package.json
examples/react-with-tailwindcss/package.json
examples/svelte/package.json
examples/vue/package.json
packages/@cva/tailwindcss/package.json
packages/class-variance-authority/package.json
packages/class-variance-authority/src/index.test.ts
packages/cva/package.json
packages/cva/src/index.test.ts
pnpm-lock.yaml

To resolve supply chain risks from the earlier – previously used – version
---

Upgrade to `typescript@5.1.3`

---

.github/actions/install/action.yml
.github/workflows/ci.yml
package.json

For each PR, generate a table of `examples/*` with StackBlitz preview links
---

Generate Examples Comment for PRs

---

packages/class-variance-authority/package.json
packages/class-variance-authority/src/index.ts
packages/cva/package.json
packages/cva/src/index.ts
pnpm-lock.yaml

- Used the named `clsx` import
- Update to `2.0.0`
---

Upgrade to `clsx@2.0.0`

---

packages/cva/src/index.test.ts

Include type tests for `compose()`
---

`compose` Type Tests

---

packages/cva/src/index.ts

Make ClassProp less ambiguous (@akomm)

---

docs/beta/theme.config.tsx
docs/latest/theme.config.tsx

`cva@beta` post-release

---

docs/beta/src/content/docs/getting-started/installation.mdx
docs/latest/pages/docs/getting-started/installation.mdx

Closes #219 (includes beta)
---

Fix neovim config

---

docs/beta/src/content/docs/api-reference.mdx

- Add `import { cx } from "cva";` to the `cx` code example for consistency.
- Update the imported function in the `defineConfig` code example.
---

docs: Update api-reference.mdx in beta docs

---

packages/cva/.config/.swcrc

As it's not recommended to ship minified code to the NPM registry
---

Remove Minification

---

docs/latest/pages/docs/faqs.mdx

Fixes a typo in the FAQ section.
---

fix(docs): typo in FAQ

---

docs/latest/pages/docs/getting-started/installation.mdx

Documentation update related to bun package manager. 
---

update docs for bun installation

---

docs/latest/pages/docs/getting-started/installation.mdx

Update IntelliSense for WebStorm in latest doc to match the beta doc
The `latest` doc is the default, and the IntelliSense for WebStorm doc needs to update. 
---

docs: Update IntelliSense for WebStorm in latest doc

---

docs/beta/src/content/docs/getting-started/installation.mdx

Simply fixing a missing comma in the tailwind merge example.
---

fix: missing comma

---

packages/class-variance-authority/package.json
packages/cva/package.json
pnpm-lock.yaml

Needing to PR some fixes on the beta and hit a couple of immediate blockers post-fork.
This will be one of a series of PR's to help ya tighten things up!
> [!NOTE]
> This PR will allow me to test my next PR that will close the issue at #256 and also help you potentially dismiss #276.
**This PR covers**:
- Yanked out bundlesize as it's severely outdated and breaks pnpm out the gate on node >v20.
- Replaced bundlesize with size-limit 🚀
- Updated package.json to support it and your github action runs.
After spending enough time with cva and getting to the point to where I'm blocked (on the beta version ofc) I'm going to spend some time helping button things up 💪.
---
--
Ping me if ya wanna chat or walk through anything! I'm on `mateothegreat` on discord or matthew@matthewdavis.io 🙏

Migrate `bundlesize` to `size-limit`
