joe-bell/cva

- .github/semantic.yml
- README.md
- Add `class` prop to README and adjust wording
- Add [semantic pull requests](https://github.com/zeke/semantic-pull-requests)
> Extend README, Enforce Semantic Commits

- src/index.test.ts
- src/index.ts
This PR aims to solve [Issue #2](https://github.com/joe-bell/cva/issues/2)
Currently, boolean variants aren't supported by the package.
With this PR, variants such as:
```js
const button = cva("button", {
variants: {
disabled: {
false: "opacity-100",
true: "opacity-050"
}
}
});
```
Could be used as native boolean variants: 
```js
button({ disabled: true })
```
Also, having both boolean & string variants work (as mentioned in the according to issue).
---
> feat: add boolean variants

- README.md
What's up 👋 
You can alias package names during installation, so it works even if you don't use TypeScript or you compile TypeScript with something that doesn't support TSConfig Paths.
It's supported since NPM 6.x (6.9 possibly?) and also in Yarn and PNPM (with way better docs).
- https://docs.npmjs.com/cli/v6/commands/npm-install
- https://classic.yarnpkg.com/lang/en/docs/cli/add/#toc-yarn-add-alias
- https://pnpm.io/aliases
Looks like this in package.json:
```json
"dependencies": {
"cva": "npm:class-variance-authority@^0.1.0"
}
```
Awesome package BTW :)
---
> Advise aliasing during install instead of TS Paths

- README.md
In the **Examples** section, the *React (with CSS Modules)* example mentions a disclaimer comment that isn't relevant for this example. 
The comment states `// ⚠️ Disclaimer: Use of Tailwind CSS is optional` although example is illustrating CSS modules usage.
---
> docs: remove unnecessary comment in README

- src/index.ts
Changes the typing of allowed values for boolean variants so that either boolean state is accepted, instead of just limiting it to the implemented values.
Fixes #21 
---
> fix: allow both boolean states for boolean variant

- README.md
- src/index.test.ts
- src/index.ts
Currently, `false` boolean variants don't work as expected. Somewhere `cva` is probably considering these variants `false` and ignoring them, rather than actually using them
Additionally, allow disabling of `defaultVariants` by passing an explicit `null`
Follow-up to #21 
---
> Fix Behaviour of Falsey Boolean Variants

- .npmignore
- src/index.ts
- src/types.ts
Fixes #27 
As much as I'd prefer to keep a single file for all code, this feels like a better trade-off than exporting types I don't want to make publicly available…
Weirdly this seems to fix a common issue when creating libraries dependent on cva 🤷 
cc @brattonross 
---
> Support Compiling TypeScript with `--declaration` Flag

- src/index.ts
Variantkey is undefined when the variant key is 0, need to handle the special case of 0.
For example, NextUI grid component use `xs=0` to hide the component.
```
xs: {
true: 'xs:grow xs:max-w-full xs:basis-0',
// this won't work, right now
0: 'xs:grow-0 xs:hidden xs:max-w-0 xs:basis-0',
1: 'xs:grow-0 xs:max-w-1/12 xs:basis-1/12'
},
```
---
> fix: variant key 0 case

- README.md
- package-lock.json
- src/index.test.ts
- src/index.ts
- src/types.ts
This PR adds support for the `className` prop alongside the existing `class` (but they cannot be used together, because well that would be silly really)
See https://github.com/joe-bell/cva/discussions/40
---
> Add Support for the `className` Prop

- README.md
- src/index.test.ts
- src/index.ts
> Follows up on @JeroenReumkens' wonderful work in #66
This PR introduces the ability to target multiple variants at once within `compoundVariants` (whilst preserving type-safety)
```ts
const button = cva("button", {
variants: {
intent: {
primary: "button--primary",
secondary: "button--secondary",
warning: "button--warning",
},
disabled: {
true: "button--disabled",
false: "button--enabled",
},
},
compoundVariants: [
{
// ✨ apply to `secondary` and `warning` intents ✨
intent: ["secondary", "warning"],
disabled: true,
class: "text-black",
},
],
});
```
#66 
---
> Target Multiple Variant Options within Compound Variants

- README.md
Most [examples](https://github.com/joe-bell/cva#examples) specify which CSS framework/methodology they illustrate, except for Astro, Svelte & Vue 3 examples.
IMHO, for consistency and clarity it can be beneficial to always mention the flavour of the CSS used in the examples (it might even incentivise people to write more examples?).
Anyway, clearly not critical, just a suggestion let me know what you think :)
---
> docs: add CSS flavour mention to examples

- .config/.syncpackrc
- .config/lint-staged.config.mjs
- .prettierrc.js
- README.md
- package.json
- packages/class-variance-authority/package.json
- packages/class-variance-authority/src/experimental/index.test.ts
- packages/class-variance-authority/src/experimental/index.ts
- packages/class-variance-authority/src/experimental/types.ts
- pnpm-lock.yaml
Introduces the `/experimental` export to develop and test `class-variance-authority@1.0.0`, whilst preserving the current stable API
> **Warning**
> Changes in `/experimental` are not protected by semver
Changes available under `/experimental`
1. **Single parameter for `cva()`**
Introduces a new `base` key instead of using the first parameter 
2. **Special keyword `"unset"` to disable a variant entirely** (instead of the current behaviour: `null`)
A future PR will allow this to be enabled/disabled
---
> Introduce `/experimental` Export

- docs/pages/docs/index.mdx
This PR fixes a broken link to vanilla-extract on the cva home page.
I noticed that the cva docs link to the variant page of the [stitches](https://stitches.dev/docs/variants) website, so I did the same for [vanilla-extract](https://vanilla-extract.style/documentation/api/style-variants/). It also seemed appropriate, given the spirit of this project.
---
> docs: fix broken vanilla-extract link

- packages/class-variance-authority/package.json
- packages/cva/package.json
I guess this is all it takes to solve #147 since the files are generated but are not present in the published files in the package
---
> fix: issue #147 where map files are not present for esm files

- packages/class-variance-authority/src/index.ts
- packages/cva/src/index.ts
When enabling `exactOptionalPropertyTypes` in tsconfig.json, a type error occurs and some features become unavailable.
Example: The following error occurs when passing a variable that can be `undefined` as an object in the argument of a cva component function.
```text
components/ui/Button/index.tsx:41:50 - error TS2412: Type 'string | undefined' is not assignable to type 'undefined' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.
41       className={buttonVariants({ variant, size, className })}
~~~~~~~~~
Found 1 error in components/ui/Button/index.tsx:41
```
This also makes it difficult to handle `defaultVariants`.
```text
components/ui/Button/index.tsx:41:33 - error TS2345: Argument of type '{ variant: "default" | "destructive" | "outline" …
```
> fix: Added explicit undefined type to support exactOptionalPropertyTypes option

- docs/pages/docs/api-reference.mdx
- docs/pages/docs/index.mdx
- packages/class-variance-authority/package.json
- packages/class-variance-authority/src/index.test.ts
- packages/class-variance-authority/src/index.ts
- packages/class-variance-authority/src/types.ts
- packages/cva/README.md
- packages/cva/package.json
- packages/cva/src/index.test.ts
- packages/cva/src/index.ts
- packages/cva/src/types.ts
- pnpm-lock.yaml
I've been keen to keep `cva` dependency-free for as long as possible, but it's really hard to justify when [`clsx`](https://github.com/lukeed/clsx) does such a better job than `cx` with **zero change** to bundle-size!
This PR:
- Provides additional support for booleans and variadic strings (closes #122) within `class` or `className` props
- Provides support for [object](https://github.com/lukeed/clsx#usage) syntax within `class` or `className` props
---
> `cx` → `clsx`

- examples/vue/package.json
- examples/vue/src/App.vue
- examples/vue/src/components/Button.vue
- pnpm-lock.yaml
- Updates Vue to 3.3.4
- Updates `@vitejs/plugin-vue` to 4.2.3
- Removes the `as any` in the Button example
- Use Vue's [withDefaults](https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits) built-in compiler macro for default values
Doing the code below will not work as Vue does not support conditional types in the entire props object:
```ts
type ButtonProps = VariantProps<typeof button>;
defineProps<ButtonProps>();
```
That's why we declare all props in the `defineProps` macro again.
---
> Bump Vue version and fix example

- docs/pages/docs/getting-started/installation.mdx
This PR adds a tutorial for enabling tailwind autocompletion inside cva in WebStorm
With the update of WebStorm to version 2023.1, support for tailwind configuration settings is now available, and I have added a note about this in the [Installation section](https://cva.style/docs/getting-started/installation) of the documentation
---
> docs: webstorm autocompletion

- packages/cva/README.md
- packages/cva/src/index.test.ts
- packages/cva/src/index.ts
Removes the `"unset"` value from `cva@1.0` in favour of a more explicit manual setup
---
> Roll-your-own `unset`

- packages/cva/README.md
- packages/cva/package.json
- packages/cva/src/index.test.ts
- packages/cva/src/index.ts
Introduces `compose()` a **shallow** merger for components
---
> Introduce `compose`

- docs/beta/pages/docs/api-reference.mdx
- docs/beta/pages/docs/getting-started/installation.mdx
- packages/cva/src/index.test.ts
- packages/cva/src/index.ts
- Not a massive fan of `cx:done` – I feel like it's an implementation detail that doesn't matter. Switching to `onComplete`!
- Fixes `compose` by making props optional
---
> Rename `cx:done` to `onComplete`, Fix `compose` Prop Types

- docs/beta/src/content/docs/index.mdx
- docs/latest/pages/docs/index.mdx
Currently [LICENSE](https://cva.style/docs#license) section in documentation site seems to be broken.
This PR fixes LICENSE broken link in documentation site.
---
> docs: fix license url

- docs/beta/src/content/docs/getting-started/installation.mdx
Fixes a very small, but potentially misleading typo in the `twMerge` [example of the beta docs](https://beta.cva.style/getting-started/installation/).
`intent` could seem like a special property, whereas in fact it's just an arbitrary name of a variant. 
---
> docs: Fix typo in `twMerge` example of beta installation docs

- .github/workflows/ci.yml
In the hopes that it'll finally solve these frustrating Sticky Comment issues
---
> Set `GITHUB_TOKEN` for Sticky Comment

- .github/workflows/ci.yml
- docs/beta/src/content/docs/getting-started/whats-new.mdx
The links in the [getting-started/whats-new](https://beta.cva.style/getting-started/whats-new/) section of the beta docs are all prefixed with `/docs` causing them to `404`.
I removed the `/docs` prefix as it is not configured that way in the starlight config.
---
> fix(docs): update broken links to getting-started pages

- packages/class-variance-authority/src/index.ts
- packages/class-variance-authority/src/types.ts
- packages/cva/src/index.ts
While I'm totally flattered by (and continue to encourage!) the number of projects extending `cva` and `class-variance-authority`, it's important to call out that this project is–and always has been–**Apache 2.0** licensed
_Personally, I've always preferred Apache 2.0 for cultivating a stronger culture of attribution within open-source_
With Apache 2.0 comes specific obligations:
> 1. You must release all the unmodified parts of the software under the same license (the Apache License)
> 2. You must include copyright and attribution notices, disclaiming warranties, and provide a copy of the license with any distribution of the software.
>
> [_Source_](https://www.mend.io/blog/top-10-apache-license-questions-answered/#:~:text=The%20Apache%202.0%20License%20is%20permissive.,under%20any%20lice …
> Add LICENSE Comments

- packages/cva/src/index.ts
Fixes #254 (hopefully)
* Updates the `ClassValue` type to match `clsx` (includes `bigint`)
* Exports all `Class*` types
This has been a particularly popular request that I've been pretty stubborn about not including; now realising that there's probably no harm in providing this
---
> Include `bigint` within `ClassValue`, export `Class*` types

- packages/cva/package.json
In retrospect this was a little aggressive and brings maintenance overhead for any future TypeScript releases – if there is an incompatibility I'll just fix it then 
---
> Loosen TypeScript dependency range

- packages/cva/package.json
- pnpm-lock.yaml
> Add `@arethetypeswrong/cli` to check for faulty exports

- packages/cva/package.json
The types field should appear first in the exports section.
https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FallbackCondition.md
> Import resolved to types through a conditional package.json export, but only after failing to resolve through an earlier condition. This behavior is a [TypeScript bug](https://github.com/microsoft/TypeScript/issues/50762). It may misrepresent the runtime behavior of this import and should not be relied upon.
Lint: https://arethetypeswrong.github.io/?p=cva%401.0.0-beta.3
Close #https://github.com/joe-bell/cva/issues/340
Resolve https://github.com/rolldown/tsdown/issues/238
---
> fix: types field should appear first in the exports section
